### ISSUE TITLE
Create new "gh-pages" branch for demo

### ISSUE THREAD

**Issue by jsejcksn** [qodesmith/time-calculator#1]
You should probably do this on all your repos that have index pages.

**Comment by qodesmith** [comment]
@jsejcksn Thanks for the input. I've [used rawgit before](https://github.com/qodesmith/typer) as a live demo (as opposed to github pages). It's an easy simple solution. I'll look into getting the rest of my repo's running with a live demo. If you'd like to check out some of my other projects, my [personal site](http://aaroncordova.xyz/) has a projects page with [live demo's](http://aaroncordova.xyz/projects) (including this calculator). Thanks again for the input!
